config/routes.rb
Rails.application.routes.draw do

  resources :charges, only: [:new, :create]


  resources :wikis do
    resources :collaborators, only: [:create, :destroy]
  end

  devise_for :users, controllers: { registrations: 'users/registrations'}


  devise_scope :user do
    patch 'user' => 'users/registrations#downgrade_user', as: :users_registration
  end

  get 'about' => 'welcome#about'

  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/collaborator.rb
class Collaborator < ApplicationRecord
  belongs_to :wiki
  belongs_to :user
end

app/controllers/collaborators_controller.rb
class CollaboratorsController < ApplicationController
  def create
    wiki = Wiki.find(params[:wiki_id])
    collaborator = wiki.collaborators.build(user_id: params[:user_id])


    if collaborator.save
      flash[:notice] = "Added #{collaborator.user.email} as a collaborator."
    else
      flash[:alert] = "Failed."
    end

    redirect_to edit_wiki_path(wiki)
  end

  def destroy
    wiki = Wiki.find(params[:wiki_id])
    collaborator = wiki.collaborators.find_by(user_id: params[:user_id])


    if collaborator.destroy
      flash[:notice] = "Removed #{collaborator.user.email} as a collaborator."
    else
      flash[:alert] = "Failed."
    end

    redirect_to edit_wiki_path(wiki)
  end
end

private

def collab_params
  params.require(:collaborator).permit(:wiki_id, :user_id)
end

app/helpers/collaborators_helper.rb
module CollaboratorsHelper
end

app/views/collaborators/_collaborators.html.erb
<br>
<div id="collaborators" class="form-group">
  <h2>Collaborators</h2>
  <table class="table">
    <thead>
      <tr>
        <th>Email</th>
        <th>Collaborate</th>
      </tr>
    </thead>
    <tbody>
      <% @users.each do |user| %>
        <% unless current_user == user || user.admin? || @wiki.user == user %>
          <tr>
            <td><%= user.email %></td>
            <% if @wiki.collaborators.where(user_id: user.id).first %>
              <td><%= link_to "Remove", wiki_collaborator_path(@wiki, user_id: user.id), method: :delete %></td>
            <% else %>
              <td><%= link_to "Add", wiki_collaborators_path(@wiki, user_id: user.id), method: :post %></td>
            <% end %>
          </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>