config/routes.rb
Rails.application.routes.draw do

  resources :charges, only: [:new, :create]


  resources :wikis do
    resources :collaborators, only: [:create, :destroy]
  end

  devise_for :users, controllers: { registrations: 'users/registrations'}


  devise_scope :user do
    patch 'user' => 'users/registrations#downgrade_user', as: :users_registration
  end

  get 'about' => 'welcome#about'

  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
  def user_is_standard_or_upgrading_member
    user_signed_in? && (current_user.role == 'standard' || current_user.role == 'upgrading')
  end
end

app/views/welcome/about.html.erb
<h1>Welcome#about</h1>
<p>Find me in app/views/welcome/about.html.erb</p>

app/views/welcome/index.html.erb
<br>
<% if !user_signed_in? %>
  <div class="jumbotron">
    <h1 class="text-center">New to Wiki-it?</h1>
    <h2 class="text-center">Choose a plan to sign up!</h2>

    <br>
    <div class="row">
      <div class="col-sm-4 col-sm-offset-1 text-center">
        <h3 class="text-center">Create unlimited public wikis!</h3>
        <br>
        <%= link_to "Standard", new_user_registration_path, :class => "btn-lg btn btn-primary"  %>
      </div>
      <div class="col-sm-4  col-sm-offset-2 text-center">
        <h3 class="text-center">Create public and private wikis!</h3>
        <br>
        <%= link_to "Premium", new_user_registration_path(role: 'premium'), :class => "btn-lg btn btn-primary"  %>
      </div>
    </div>
  </div>
<% end %>
  <div class="jumbotron">
    <h1>Wiki-it</h1>
    <p>Create and share Markdown Wikis with the world. Contribute to the wiki platform and become part of the community.</p>
    <% if user_signed_in? %>
      <%= link_to "Edit Profile", edit_user_registration_path, :class => "btn-md btn btn-primary"  %>
    <% end %>
  </div>
  <br>
  <div class="row">
    <div class="col-md-4">
      <h2>Solves world hunger</h2>
      <p>Wiki-it will deliver food and water to those in need, all over the world.</p>
    </div>
    <div class="col-md-4">
      <h2>Eliminates poverty</h2>
      <p>Wiki-it will deliver money and education to those in need, all over the world.</p>
    </div>
    <div class="col-md-4">
      <h2>Makes you better looking</h2>
      <p>Wiki-it will make you better looking: it's scientifically proven to make men look like Ryan Gosling and women look like Shakira.</p>
    </div>
  </div>
<br>
  <% if user_is_standard_or_upgrading_member %>
    <div class="jumbotron text-center">
      <h2 class="text-center">Upgrade to a Premium membership to create and see private wikis.</h2>
      <br>
      <%= link_to "Upgrade", new_charge_path, :class => "btn-lg btn btn-primary"  %>
    </div>
  <% end %>