config/routes.rb
Rails.application.routes.draw do

  resources :charges, only: [:new, :create]


  resources :wikis do
    resources :collaborators, only: [:create, :destroy]
  end

  devise_for :users, controllers: { registrations: 'users/registrations'}


  devise_scope :user do
    patch 'user' => 'users/registrations#downgrade_user', as: :users_registration
  end

  get 'about' => 'welcome#about'

  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/wiki.rb
class Wiki < ApplicationRecord
  # before_save :validate_user
  belongs_to :user
  has_many :collaborators, dependent: :destroy

  validates :user, presence: true
end

app/controllers/wikis_controller.rb
class WikisController < ApplicationController
  before_action :authenticate_user!, except: [:show, :index]
  before_action :user_is_admin_or_wiki_owner?, only: :destroy
  before_action :user_is_authorized_for_private_wikis?, only: [:show, :edit]
  require 'redcarpet/compat'

  def index
    @wikis = policy_scope(Wiki)
  end

  def show
    @wiki = Wiki.find(params[:id])
  end

  def new
    @wiki = Wiki.new
  end

  def create
    @wiki = Wiki.new(wiki_params)
    @wiki.user = current_user

    if @wiki.save
      flash[:notice] = "Wiki was saved."
      redirect_to @wiki
    else
      flash.now[:alert] = "There was an error saving the wiki. Please try again."
      render :new
    end
  end

  def edit
    @wiki = Wiki.find(params[:id])
    @users = User.all
  end

  def update
    @wiki = Wiki.find(params[:id])
    @wiki.assign_attributes(wiki_params)
    if @wiki.save
      flash.now[:notice] = "Wiki was updated."
      respond_to do |format|
        format.js { render layout: false }
        format.html { redirect_to @wiki }
      end
    else
      flash.now[:alert] = "There was an error saving the wiki. Please try again."
      render :edit
    end
  end

  def destroy
    @wiki = Wiki.find(params[:id])

    if @wiki.destroy
      flash[:notice] = "\"#{@wiki.title}\" was deleted successfully."
      redirect_to wikis_path
    else
      flash.now[:alert] = "There was an error deleting the wiki."
      render :show
    end
  end

  private

  def wiki_params
    params.require(:wiki).permit(:title, :body, :private)
  end

  def user_is_admin_or_wiki_owner?
    wiki = Wiki.find(params[:id])

    unless current_user.admin? || current_user == wiki.user
      flash[:alert] = "You must be an admin to do that."
      redirect_to wikis_path
    end
  end

   def user_is_authorized_for_private_wikis?
    wiki = Wiki.find(params[:id])
    unless (wiki.private == false ||
    current_user.try(:admin?) ||
    wiki.collaborators.find_by(user_id: current_user.try(:id)) ||
    current_user == wiki.user)
      flash[:alert] = "You are unauthorized to see private wikis."
      redirect_to wikis_path
    end
  end
end

app/helpers/wikis_helper.rb
module WikisHelper
  def user_is_authorized_for_wiki?(wiki)
    current_user && (current_user == wiki.user || current_user.admin?)
  end

  def user_is_admin_or_wiki_owner(wiki)
    current_user.admin? || current_user == wiki.user
  end
end

app/views/wikis/_form.html.erb
<div class="col-md-8">
  <%= form_for @wiki do |f| %>
    <div class="form-group">
      <%= f.label :title %>
      <%= f.text_field :title, class: 'form-control', placeholder: "Enter wiki title" %>
    </div>
    <div class="form-group">
      <%= f.label :body %>
      <%= f.text_area :body, placeholder: "Enter wiki body", class: 'form-control', rows: 8 %>
    </div>
    <% if current_user.admin? || (current_user.premium? && current_user == @wiki.user || !@wiki.user) %>
      <div class="form-group checkbox">
        <%= f.label :private do %>
          <%= f.check_box :private %> Private
        <% end %>
      </div>
    <% end %>
    <div class="form-group">
      <%= f.submit "Save", class: "btn btn-success" %>
    </div>
    <% if @users and user_is_admin_or_wiki_owner(@wiki) %>
      <%= render partial: 'collaborators/collaborators' %>
    <% end %>
  <% end %>
</div>


<script type="text/javascript">
  $(document).ready(function() {
    if(!$('#wiki_private').is(':checked')) {
      $('#collaborators').hide();
    }

    $('#wiki_private').change(function() {
      console.log($(this).is(':checked'));
      $.ajax({
        url: $('.edit_wiki').attr('action'),
        type: 'PUT',
        data: {wiki: {private: $(this).is(':checked')}}
      })
    });
  });
</script>

app/views/wikis/edit.html.erb
<h1>Edit Wiki</h1>

<div class="row">
  <div class="col-md-4">
    <p>Guidelines for wikis</p>
    <ul>
      <li>You can use markdown for your wikis</li>
      <li>Keep the usage of foul language to a minimum</li>
      <li>Harassment of any sort will get you banned</li>
    </ul>
  </div>
  <%= render partial: 'form' %>
</div>

app/views/wikis/index.html.erb
<h1>All Wikis</h1>
<br>
<div class="row">
  <div class="col-md-8">
    <% @wikis.each do |wiki| %>
      <div class="media">
        <div class="media-body">
          <h4 class="media-heading">
            <%= link_to wiki.title, wiki %>
          </h4>
          <small>
            submitted by <%= wiki.user.email %><br> <%= time_ago_in_words(wiki.created_at) %> ago |
            <% if wiki.private %>
              private
            <% else %>
              public
            <% end %>
          </small>
        </div>
      </div>
    <% end %>
  </div>
  <br >
  <% if user_signed_in? %>
    <div class "col-md-4">
      <%= link_to "New Wiki", new_wiki_path, class: 'btn btn-success' %>
    </div>
  <% end %>
</div>

app/views/wikis/new.html.erb
<h1>New Wiki</h1>

<div class="row">
  <div class="col-md-4">
    <p>Guidelines for wikis</p>
    <ul>
      <li>Keep it simple</li>
      <li>Don't use vulgar language</li>
      <li>Harassment of any sort will get you banned</li>
    </ul>
  </div>
  <%= render partial: 'form' %>
</div>

app/views/wikis/show.html.erb
<h1>
  <%= @wiki.title %> <br>
  <small>
    submitted <%= time_ago_in_words(@wiki.created_at) %> ago by <%= @wiki.user.email %>
  </small>
</h1>
<div class="row">
  <div class="col-md-8">
    <p><%= Markdown.new(@wiki.body).to_html.html_safe %></p>
  </div>
  <br>
  <% if user_signed_in? %>
    <div class="col-md-4">
      <%= link_to "Edit", edit_wiki_path(@wiki), class: 'btn btn-success' %>
      <% if user_is_authorized_for_wiki?(@wiki) %>
        <%= link_to "Delete Post", @wiki, method: :delete, class: 'btn btn-danger', data: {confirm: 'Are you sure you want to delete this wiki?'} %>
      <% end %>
    </div>
  <% end %>
</div>

app/views/wikis/update.js.erb
<% if @wiki.private? %>
  $('#collaborators').show();
<% else %>
  $('#collaborators').hide();
<% end %>